# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'bento/centos-7.3'
  # config.vm.provision :shell, path: 'install-common-package.sh'
  # config.vm.provision :shell, path: 'install-elasticsearch.sh'

  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--memory', '1024']
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook       = 'playbook.yml'
    ansible.raw_ssh_args   = ['-o ForwardAgent=yes']
    # ansible.groups = {
    #   'vagrant' => ['server']
    # }
  end

  (1..3).each do |i|
    node_name = "node-#{i}"
    config.vm.define node_name do |subconfig|
      subconfig.vm.hostname = node_name
      subconfig.vm.network :private_network, ip: "192.168.33.1#{i}"
      # subconfig.vm.provision :shell do |s|
      #   s.path = 'set-elasticsearch.sh'
      #   s.args = node_name
      # end
    end
  end
end
